version: "3"
services:
  app:
    build: .
    ports:
    - 80:3000
    volumes:
    - ".:/go/src/github.com/JYama321/penguin_bbs"
    command: sh ./start_app.sh
    depends_on:
    - db
  db:
    image: mysql:5.7
    ports:
    - 3306:3306
    env_file:
    - mysql/db.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
    #      - mysql-data:/var/lib/mysql
    - ./mysql/sql:/docker-entrypoint-initdb.d
volumes:
  db-data: